
// Automatically generated by extract-default-properties.mjs

import {
  type LayoutProperties,
  type CostWeights
} from "./layout.js";

export const DEFAULT_PROPERTIES = {
  bellTipShape: 0.1,
  bellTipSpread: 0.5,
  bellStrokeWidth: 1,
  bellPlateauPos: 0.75,
  sampleHeight: 110,
  sampleWidth: 90,
  inferredSampleHeight: 120,
  gapHeight: 60,
  sampleSpacing: 60,
  columnSpacing: 90,
  tentacleWidth: 2,
  tentacleSpacing: 5,
  inOutCPDistance: 0.3,
  bundleCPDistance: 0.6,
  sampleFontSize: 12,
  showLegend: true,
  phylogenyColorScheme: true,
  phylogenyHueOffset: 0,
  sampleTakenGuide: "text"
} as LayoutProperties;

export const DEFAULT_COST_WEIGHTS = {
  crossing: 10,
  pathLength: 2,
  orderMismatch: 2,
  bundleMismatch: 3,
  divergence: 4
} as CostWeights;
